export * from './assigments.validator.js'
export * from './courses.validator.js'
export * from './students.validator.js'
export * from './teachers.validator.js'
export * from './users.validator.js'
export * from './homework.validator.js'
export * from './lessons.validator.js'
export * from './exam.validator.js'